# Generated by Django 4.1.7 on 2023-03-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rank", models.IntegerField()),
                ("album", models.CharField(blank=True, default="", max_length=255)),
                ("writers", models.TextField()),
                ("singer", models.CharField(max_length=255)),
                ("release_year", models.IntegerField()),
                ("song_time", models.IntegerField()),
                ("spotify_streams", models.IntegerField(default=0)),
                ("rolling_stone_rank", models.IntegerField(blank=True, null=True)),
                ("nme_rank", models.IntegerField(blank=True, null=True)),
                ("ug_views", models.IntegerField(default=0)),
                ("ug_favourites", models.IntegerField(default=0)),
            ],
        ),
    ]
