# Generated by Django 4.1.7 on 2023-03-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_alter_song_name_alter_song_nme_rank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="nme_rank",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="NME Top 50 Rank"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="rolling_stone_rank",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Rolling Stone Top 100 Rank"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="song_time",
            field=models.IntegerField(verbose_name="Song Time"),
        ),
    ]
