# Generated by Django 4.1.7 on 2023-03-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0003_alter_song_nme_rank_alter_song_rolling_stone_rank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="song_time",
            field=models.IntegerField(
                help_text="The duration of the song in seconds.",
                verbose_name="Song Time",
            ),
        ),
    ]
