# Generated by Django 4.1.7 on 2023-03-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0004_alter_song_song_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="singer",
            field=models.TextField(),
        ),
    ]
