# Generated by Django 4.1.7 on 2023-03-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0005_alter_song_singer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="ug_favourites",
            field=models.IntegerField(
                default=0, verbose_name="Favourites on Ultimate Guitar"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="ug_views",
            field=models.IntegerField(
                default=0, verbose_name="Views on Ultimate Guitar"
            ),
        ),
    ]
