# Generated by Django 4.1.7 on 2023-03-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0006_alter_song_ug_favourites_alter_song_ug_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="ug_favourites",
            field=models.IntegerField(
                default=0, verbose_name="Ultimate Guitar Favourites"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="ug_views",
            field=models.IntegerField(default=0, verbose_name="Ultimate Guitar Views"),
        ),
    ]
